In [1]:
ipsource_dict = {0: 'M', 1: 'R', 2: 'A', 3: 'X'}
label_dict = {0: 'G', 1: 'R',2: 'U'}

In [2]:
import pandas as pd

training = pd.read_pickle("../data/dataset_b_noisy_7_agents_training.pkl") 
test_comb = pd.read_pickle("../data/dataset_b_noisy_7_agents_test.pkl")

In [3]:
training.head()

,srcAS,destAS,srcCC,destCC,num_hops,lat,long,IPsource,geoCC,ASN,gpl,gpo,vf,label_comb
trid,,,,,,,,,,,,,,
1328731,14061,42999,US,TR,10,"[50.115520000000004, 50.115520000000004, 50.11...","[8.68417, 8.68417, 8.68417, 8.67185, 9.491, 8....","[0, 1, 0, 0, 2, 0, 2, 2, 1, 2]","[DE, DE, DE, DE, DE, DE, TR, TR, TR, TR]","[14061, 14061, 2914, 2914, 2914, 9121, 9121, 9...",0,0,0,0
5183622,138062,3605,ID,GU,1,[22.285521],[114.1577],[0],[HK],[24482],0,0,0,0
3258755,14061,24173,US,VN,10,"[40.714271999999994, 40.714271999999994, 40.71...","[-74.005966, -74.005966, -74.005997, -122.3320...","[0, 0, 0, 0, 0, 0, 0, 2, 2, 2]","[US, US, US, US, JP, HK, HK, HK, VN, VN]","[14061, 14061, 2914, 2914, 2914, 2914, 2914, 2...",0,0,0,0
2660757,16276,7171,FR,US,13,"[0.0, 0.0, 0.0, 0.0, 1.28967, 43.296669, 48.86...","[0.0, 0.0, 0.0, 0.0, 103.850098, 5.37639, 2.34...","[3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[nan, nan, nan, nan, SG, FR, FR, FR, FR, US, U...","[0, 0, 0, 0, 16276, 16276, 16276, 6461, 6461, ...",0,0,0,0
1730541,20473,12479,US,ES,7,"[48.860001000000004, 48.860001000000004, 48.86...","[2.34444, 2.34444, 2.34444, 5.381069999999999,...","[0, 0, 0, 1, 0, 0, 0]","[FR, FR, FR, FR, ES, ES, ES]","[3257, 3257, 3257, 5511, 5511, 5511, 5511]",0,0,0,0

In [4]:
test_comb.head()

,srcAS,destAS,srcCC,destCC,num_hops,lat,long,IPsource,geoCC,ASN,gpl,gpo,vf,label_comb
trid,,,,,,,,,,,,,,
4319757,8551,6147,IL,PE,12,"[32.080878999999996, 32.080878999999996, 50.11...","[34.780571, 34.780571, 8.68417, 8.67185, 8.671...","[1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2]","[IL, IL, DE, DE, DE, GB, GB, US, US, ES, ES, PE]","[8551, 8551, 8551, 8551, 3257, 3257, 3257, 129...",0,0,0,0
3971404,8551,9121,IL,TR,13,"[32.080878999999996, 32.080878999999996, 32.08...","[34.780571, 34.780571, 34.780571, -0.125740000...","[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]","[IL, IL, IL, GB, GB, GB, GB, GB, NL, NL, NL, N...","[8551, 8551, 8551, 8551, 3257, 3257, 2914, 291...",0,0,0,0
4094951,8551,9583,IL,IN,8,"[32.080878999999996, 32.080878999999996, 32.08...","[34.780571, 34.780571, 34.780571, -0.125740000...","[1, 1, 1, 0, 3, 3, 3, 3]","[IL, IL, IL, GB, nan, nan, nan, nan]","[8551, 8551, 8551, 9583, 0, 0, 0, 0]",0,0,0,0
1619804,20473,393396,US,US,8,"[48.860001000000004, 48.860001000000004, 48.86...","[2.34444, 2.34444, 2.34444, 10.7487, 2.34444, ...","[0, 0, 0, 2, 0, 0, 0, 2]","[FR, FR, FR, NO, FR, FR, US, US]","[1299, 1299, 1299, 3356, 3356, 3356, 3549, 393...",0,0,0,0
1353363,14061,29465,US,NG,10,"[50.115520000000004, 50.115520000000004, 50.11...","[8.68417, 8.68417, 8.67185, 8.67185, 2.34444, ...","[1, 0, 0, 0, 0, 0, 0, 0, 2, 2]","[DE, DE, DE, DE, FR, GB, GB, GB, NG, NG]","[14061, 14061, 1299, 1299, 1299, 1299, 1299, 1...",0,0,0,0

In [5]:
print(training['gpl'].value_counts())
print(training['gpo'].value_counts())
print(training['vf'].value_counts())
print(training['label_comb'].value_counts())

0    2710641
1      86408
2       5752
Name: gpl, dtype: int64
0    2782961
1      19338
2        502
Name: gpo, dtype: int64
0    2727069
2      37986
1      37746
Name: vf, dtype: int64
0    2666724
1     136077
Name: label_comb, dtype: int64

In [6]:
print(test_comb['gpl'].value_counts())
print(test_comb['gpo'].value_counts())
print(test_comb['vf'].value_counts())
print(test_comb['label_comb'].value_counts())

0    679078
1     21788
2      1517
Name: gpl, dtype: int64
0    697340
1      4905
2       138
Name: gpo, dtype: int64
0    683333
2      9542
1      9508
Name: vf, dtype: int64
0    668035
1     34348
Name: label_comb, dtype: int64